variable "accept_marketing_emails" {
  default     = false
  description = "Whether to accept marketing emails or not."
}

variable "account_password" {
  description = "Password of the SendGrid account. Autogenerated if not specified."
  default     = null
  type        = string
}

variable "account_password_length" {
  description = "Length of the autogenerated password for SendGrid account."
  default     = 20
}

variable "company" {
  default     = ""
  description = "Company name."
}

variable "key_vault_resource" {
  description = "Azure Key Vault resource with ID property. SendGrid account credentials and server name will be stored as secrets in it if set."
  default     = null
  type        = object({ id = string })
}

variable "key_vault_secret_name_account_password" {
  description = "Azure Key Vault secret name which will hold the password value for SendGrid account."
  default     = "SendgridAdminAccountPassword"

  validation {
    condition = (
      can(regex("^[a-zA-Z0-9-]{1,127}$", var.key_vault_secret_name_account_password))
    )
    error_message = "Value isn't valid."
  }
}

variable "key_vault_secret_name_account_username" {
  description = "Azure Key Vault secret name which will hold the username value for SendGrid account."
  default     = "SendgridAdminAccountUsername"

  validation {
    condition = (
      can(regex("^[a-zA-Z0-9-]{1,127}$", var.key_vault_secret_name_account_username))
    )
    error_message = "Value isn't valid."
  }
}

variable "key_vault_secret_name_server_name" {
  description = "Azure Key Vault secret name which will hold the value for SendGrid server name."
  default     = "SendgridServerName"

  validation {
    condition = (
      can(regex("^[a-zA-Z0-9-]{1,127}$", var.key_vault_secret_name_server_name))
    )
    error_message = "Value isn't valid."
  }
}

variable "location" {
  description = "Location where resources will be created. Either combo of this + var.resource_group_name or var.resource_group_resource should be provided."
  default     = null
  type        = string
}

variable "name" {
  description = "SendGrid account resource name."
  type        = string

  validation {
    condition     = length(var.name) >= 4 && length(var.name) <= 50
    error_message = "Value length should be between 4-50 chars inclusive."
  }
}

variable "resource_group_name" {
  description = "Name of the new resource group to host sendgrid account. Either combo of this + var.location or var.resource_group_resource should be provided."
  default     = null
  type        = string
}

variable "resource_group_resource" {
  description = "Partial existing resource group resource with keys for its name and location. Either this or combo of var.resource_group_name and var.location should be provided."
  default     = null
  type        = object({ name = string, location = string })
}

variable "plan_name" {
  default     = "free"
  description = "SendGrid plan name."

  validation {
    condition = (
      contains(
        [
          "free",
          "bronze",
          "silver",
          "gold",
          "platinum",
          "premier",
        ],
        var.plan_name
      )
    )
    error_message = "Value isn't valid."
  }
}

variable "plan_product" {
  default     = "sendgrid_azure"
  description = "SendGrid plan id."

  validation {
    condition     = var.plan_product == "sendgrid_azure"
    error_message = "Only 'sendgrid_azure' value is supported."
  }
}

variable "plan_promotion_code" {
  default     = ""
  description = "SendGrid plan promotion code."
}

variable "plan_publisher" {
  default     = "sendgrid"
  description = "SendGrid publisher name."

  validation {
    condition     = var.plan_publisher == "sendgrid"
    error_message = "Only 'sendgrid' value is supported."
  }
}

variable "tags" {
  description = "Tags to organize Azure resources."
  default     = {}
  type        = map(string)
}

variable "user_email" {
  default     = ""
  description = "E-mail of the subscriber."
}

variable "user_first_name" {
  default     = ""
  description = "First name of the subscriber."
}

variable "user_last_name" {
  default     = ""
  description = "Last name of the subscriber."
}

variable "website" {
  default     = ""
  description = "Website url."
}
